# Generated by Django 4.1.3 on 2022-12-07 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niu_db', '0002_ticket_ticket_ticket_one_ticket_ticket_two'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='twoCol',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='twoRow',
            field=models.SmallIntegerField(null=True),
        ),
    ]
