# Generated by Django 4.1.3 on 2022-12-07 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('niu_db', '0003_alter_ticket_twocol_alter_ticket_tworow'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
