# Generated by Django 4.1.3 on 2022-12-07 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niu_db', '0004_delete_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('studentID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('seatOne', models.CharField(max_length=6)),
                ('seatTwo', models.CharField(max_length=6, null=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(fields=('seatOne', 'seatTwo'), name='seat'),
        ),
    ]
