# Generated by Django 4.1.3 on 2022-12-07 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niu_db', '0005_ticket_ticket_seat'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ticket',
            name='seat',
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(fields=('seatOne', 'seatTwo'), name='seat1'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(fields=('seatOne',), name='seat2'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(fields=('seatTwo',), name='seat3'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(fields=('seatTwo', 'seatOne'), name='seat4'),
        ),
    ]
