# Generated by Django 4.1.4 on 2022-12-23 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('niu_db', '0009_ticket_uuid_ticket_studentid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
