# Generated by Django 4.1.4 on 2022-12-23 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niu_db', '0010_delete_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('seat', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('studentID', models.CharField(max_length=12)),
                ('name', models.CharField(max_length=20)),
                ('cusuuid', models.CharField(max_length=8)),
            ],
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(fields=('seat',), name='seat'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(fields=('studentID',), name='studentID'),
        ),
    ]
