# Generated by Django 4.1.4 on 2022-12-23 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('niu_db', '0011_ticket_ticket_seat_ticket_studentid'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ticket',
            name='studentID',
        ),
    ]
