# Generated by Django 4.1.4 on 2022-12-29 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niu_db', '0012_remove_ticket_studentid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('account', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=12)),
            ],
        ),
    ]
